version: '3.7'

services:
  backend:
    image: ghcr.io/codemate-oj/codemate-core/backend:latest
    ports:
      - "8888:8888"
    restart: always
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
