name: CI

on:
- push
- pull_request

env:
  CI: true
  YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 2
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - uses: actions/cache@v3
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          yarn.lock
          .cache
          **/tsconfig.tsbuildinfo
        key: cache-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          cache-${{ github.ref }}-
          cache-
    - name: Clear Cache
      if: contains(github.event.head_commit.message, 'skip-cache')
      run: |
        rm -rf node_modules yarn.lock **/tsconfig.tsbuildinfo
    - name: Install Dependencies
      run: |
        yarn
        yarn dedupe
    - name: Lint
      run: |
        yarn build:ui:gulp
        parallel --tty -j+0 yarn ::: lint:ci lint:ui:ci
    - name: Run Unit Test
      run: yarn test
    # Steps below are omitted cuz docker will do the same thing.
    # - name: Build UI
    #   run: yarn build:ui:production:webpack
    # - name: Build
    #   run: |
    #     yarn build
  build-docker:
    needs: test-and-lint
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Image & Push
      uses: docker/build-push-action@v2
      with:
        # push: true
        context: .
        tags: docker.pkg.github.com/codemate-oj/codemate-core/backend:${{ github.sha }}
