name: Deploy To Test Environment
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to develop
      uses: appleboy/ssh-action@master
      with:
        host: 43.139.233.159
        port: 22
        username: ubuntu
        password: ${{ secrets.DEPLOY_SECRET }}
        script: sudo su -c 'cd /root/codemate-core/ && git pull && /root/.nvm/versions/node/v20.13.1/bin/pm2 restart all'
