name: Deploy To Test Environment
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to develop
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        username: ubuntu
        password: ${{ secrets.SERVER_PASSWORD }}
        script: sudo su -c 'cd /root/codemate-core/ && git pull && pm2 reload hydrooj'
