name: deploy

concurrency: production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-docker:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Image & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: docker.pkg.github.com/codemate-oj/codemate-core/backend:latest

  deploy-test:
    name: Deploy-Test
    runs-on: [self-hosted]
    # i know this is wierd, but it works
    steps:
      - name: Change Work Dir & Install
        run: |
          sudo su root
          cd ~/codemate-core
          yarn
      # - uses: actions/checkout@v3
      #   name: Check Out
      #   with:
      #     submodules: recursive
      # - name: Get specific changed files
      #   id: ui-changed-files
      #   uses: tj-actions/changed-files@v41
      #   with:
      #     files: |
      #       /package.json
      #       .eslint*
      #       packages/ui-default/**
      #       packages/utils/**
      #       .github/workflows/**
      - name: Install & Build UI
        if: steps.ui-changed-files.outputs.any_changed
        run: |
          yarn build:ui:production
      - name: Restart Server
        run: pm2 restart hydrooj

