name: deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to develop
      uses: appleboy/ssh-action@master
      with:
        host: http://43.139.233.159/
        username: ubuntu
        key: ${{ secrets.DEPLOY_SECRET }}
        port: 22
        script: sudo su -c 'cd /root/codemate-core/ && git pull && /root/.nvm/versions/node/v20.13.1/bin/pm2 restart all'
