name: deploy

concurrency: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_to_test:
    name: Deploy-Test
    runs-on: [self-hosted, test1]
    steps:
      - uses: actions/checkout@v3
        name: Check Out
        with:
          submodules: recursive
      - name: Build Image & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          load: true
          context: .
          tags: docker.pkg.github.com/codemate-oj/codemate-core/backend:latest

